DROP DATABASE IF EXISTS test;
CREATE DATABASE test;

USE test;

CREATE TABLE users(
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	created_at DATETIME NULL,
	updated_at DATETIME NULL
);

INSERT INTO users(created_at, updated_at) VALUES 
(DEFAULT, DEFAULT),
(DEFAULT, DEFAULT),
(DEFAULT, DEFAULT),
(DEFAULT, DEFAULT),
(DEFAULT, DEFAULT);

UPDATE users SET created_at = NOW(), updated_at = NOW();
